-- Run this in Supabase SQL Editor
-- Sets the secret admin password used by custom admin flows.

create table if not exists public.admin_secrets (
  id bigint generated by default as identity primary key,
  master_password text,
  secret_admin_password text,
  created_at timestamptz not null default now()
);

alter table public.admin_secrets
  add column if not exists secret_admin_password text;

update public.admin_secrets
set secret_admin_password = 'Aquackeck123';

insert into public.admin_secrets (secret_admin_password)
select 'Aquackeck123'
where not exists (select 1 from public.admin_secrets);
